swiftmailer:
    transport: gmail
    username: oumaymalyna.khaznaji@esprit.tn
    password: 191JFT2725
    host: localhost
    port: 465
    encryption: ssl
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false